config/routes.rb
Rails.application.routes.draw do
  root "chatroom#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "signup", to: "users#new"
  resources :users, except: [:delete]
  post "message", to: "messages#create"

  mount ActionCable.server, at: "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(created_at: :desc).limit(20).reverse }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 15 }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

  def require_no_user
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
      head :ok
    else
      head :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: "message", locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_user, only: [:new, :create]
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to root_path
    else
      flash.now[:error] = "There was something wrong with your login details"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out successfully"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :require_no_user, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the MessageMe family!"
      redirect_to root_path
    else
      flash.now[:error] = "Something went wrong"
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to user_path(@user)
    else
      flash.now[:error] = "Something went wrong"
      render "edit"
    end
  end

  def index
    @users = User.all
  end

  def destroy
    if @user == current_user
      @user.destroy
      session[:user_id] = nil
      flash[:success] = "Account deleted successfully"
      redirect_to root_path
    else
      flash[:error] = "You can only delete your own account"
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "Something went wrong while trying to find the user"
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="circular coffee teal icon"></i>
  Something
</h2>

<div class="ui two column stackable grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content messages-scroll">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_with(model: @message, url: message_path, class: "ui reply form") do |f| %>
          <div class="ui fluid blue icon input">
            <%= f.text_field :body, placeholder: "Enter a message..." %>
            <%= f.button '<i class="bordered inverted teal edit icon"></i>'.html_safe %>
          </div>
        <% end %>
      </div>
    </div>
</div>

  <div class="four wide column">
    <div class="ui fluid raised segment chatbox">
      <div class="ui inverted vertical fluid menu">
        <a class="active item">
          Home
        </a>
        <a class="item">
          Messages
        </a>
        <a class="item">
          Friends
        </a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <% 
    # Mapear tipos de flash do Rails para tipos do Semantic UI
    semantic_type = case message_type.to_s
    when 'notice'
      'success'
    when 'alert'
      'error'
    when 'error'
      'error'
    when 'success'
      'success'
    else
      message_type.to_s
    end
  %>
  <div class="ui <%= semantic_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", root_path, class: "item" %>
  <a class="item">
    Messages
  </a>
  <div class="right menu">
    <% if logged_in? %>
      <div class="ui dropdown item">
        <%= current_user.username %> <i class="dropdown icon"></i>
        <div class="menu">
          <%= link_to "Log out", logout_path, method: :delete, class: "item" %>
        </div>
      </div>
    <% else %>
      <%= link_to "Log in", login_path, class: "item" %>
      <%= link_to "Sign Up", signup_path, class: "ui primary button" %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag asset_path('mug-saucer-solid-full.svg') %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %>:</em> <%= sanitize(message.body) %>
    </div>
  </div>
</div>